development:
  adapter: postgres
  database: actionitems_development
  username: actionitems

test:
  adapter: postgres
  database: actionitems_test
  username: actionitems

jasmine:
  adapter: postgres
  database: actionitems_jasmine
  username: actionitems

demo:
  adapter: postgres
  database: actionitems_demo
  username: actionitems

production:
  adapter: postgres
  database: actionitems_production
  username: actionitems
